### ISSUE TITLE
Can you provide the Piano-e-competition dataset?

### ISSUE THREAD

**Issue by zhanh-he** [sappho192/midi-velocity-infer-v2#2]
Hi, I want to compare my newly built model with yours and previous works. Would you provide the Piano-e-Competition dataset used in your Table.2, so that I can make the same quantitative assessment?

I think the "Piano-e-Competition" dataset has a default train/test split right? Otherwise, providing your (Kuo's) test set will be great!

Many thanks, Zhanh

**Comment by sappho192** [comment]
@zhanh-he 
Hi, sorry for the late reply, and thank you for the contact.
I'm pleased that there's someone who are interested in this topic.

I've sent you an email containing the link to the dataset you mentioned.

Please inform me when you have released your paper. I'll look forward to your work!

**Comment by zhanh-he** [comment]
Hi Kim,

A great thanks for your providing resources! Will let you know ASAP it
happens.

Best wishes,
Zhanh
